# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 18:13
from __future__ import unicode_literals

import atfl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(default='ads.txt', help_text="Click 'Choose File' to select an ads.txt file from your local hard drive. The file on your hard drive MUST be named 'ads.txt' and be less than 100KB in size.", max_length=7)),
                ('file', models.FileField(null=True, upload_to='', validators=[atfl.models.validateFileName, atfl.models.validateFileSize])),
            ],
        ),
    ]
